language: csharp
branches:
  only:
    - travis
    - master
solution: WebHdfs.sln
install:
  - nuget restore
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release /v:m /p:restorepackages=false WebHdfs.sln
  - mono ./packages/OpenCover.4.5.3723/OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe" -targetdir:"WebHdfs.Test/bin/Release" -targetargs:"WebHdfs.Test.dll" -output:./coverage.xml -returntargetcode
after_success:
  - pip install --user codecov
  - codecov -f "coverage.xml"
