version: '{branch}-0.{build}'
branches:
  only:
  - appveyor
  - release
skip_tags: true
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: HocFG7JOlosaliJO/ea9PDMhkeWKV/yzh+Iu2UHbBBGgl724xgG7UiBY8tV90rG6
before_build:
- nuget restore
build:
  project: WebHdfs.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
after_test: 
    - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"nunit-console.exe" -targetdir:"WebHdfs.Test/bin/Release" -targetargs:"WebHdfs.Test.dll" -output:coverage.xml
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
deploy:
- provider: NuGet
  api_key:
    secure: 1La37V7bRU+XrV/GRhP2iqT0VuU1O7RAGZPTtb/Bm5Trqms8iRbIwBW/Y8IQsmVl
  on:
    branch: release

